name: Daily README Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with timestamp
        run: |
          TIMESTAMP=$(date)
          echo "<!-- Last updated: $TIMESTAMP -->" >> README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "🌱 Daily README update: $TIMESTAMP"
          git push
