name: 📄 Auto-update Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Auto update timestamp in README
        run: |
          TIMESTAMP=$(date -u)
          sed -i "s|<!--TIMESTAMP-->.*|<!--TIMESTAMP-->  $TIMESTAMP 🕒|g" README.md
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Commit and Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "sangya-25"
          git config --global user.email "158825993+sangya-25@users.noreply.github.com"
          git add README.md
          git commit -m "🕒 Auto-update: $TIMESTAMP" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
